// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | TeamSlice
  | FreeTrialSlice
  | ProgramSlice
  | WelcomeSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TrainingSlice
  | GalleryPageSlice
  | PlayersSlice
  | ContactSlice
  | AboutSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Heading field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigations*
 */
export interface SettingsDocumentDataNavigationsItem {
  /**
   * Link Label field in *Settings → Navigations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigations[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigations[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Site Slogan field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_slogan
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_slogan: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigations field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigations: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationsItem>
  >;

  /**
   * Contact Number Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_number_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_number_label: prismic.KeyTextField;

  /**
   * Contact Number field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_number: prismic.LinkField;

  /**
   * Contact Email Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_email_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_email_label: prismic.KeyTextField;

  /**
   * Contact Email field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_email: prismic.LinkField;

  /**
   * CTA Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *About → Default → Primary → About Cards*
 */
export interface AboutSliceDefaultPrimaryAboutCardsItem {
  /**
   * Image field in *About → Default → Primary → About Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Icon field in *About → Default → Primary → About Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_cards[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *About → Default → Primary → About Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_cards[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Default → Primary → About Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *About → Default → Primary → Trainer*
 */
export interface AboutSliceDefaultPrimaryTrainerItem {
  /**
   * Trainer Image field in *About → Default → Primary → Trainer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.trainer[].trainer_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  trainer_image: prismic.ImageField<never>;

  /**
   * Trainer Name field in *About → Default → Primary → Trainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.trainer[].trainer_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trainer_name: prismic.KeyTextField;

  /**
   * Trainer Title field in *About → Default → Primary → Trainer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.trainer[].trainer_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trainer_title: prismic.KeyTextField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * About Cards field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  about_cards: prismic.GroupField<
    Simplify<AboutSliceDefaultPrimaryAboutCardsItem>
  >;

  /**
   * Background Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Sub Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *About → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Trainer Title field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.trainer_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trainer_title: prismic.KeyTextField;

  /**
   * Trainer field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.trainer[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  trainer: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryTrainerItem>>;

  /**
   * Newsletter Title field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.newsletter_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_title: prismic.KeyTextField;

  /**
   * NewsletterDiscription field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.newsletterdiscription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterdiscription: prismic.RichTextField;

  /**
   * Newsletter Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.newsletter_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  newsletter_image: prismic.ImageField<never>;

  /**
   * Newsletter Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.newsletter_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_heading: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Blog → Default → Primary → Blog*
 */
export interface BlogSliceDefaultPrimaryBlogItem {
  /**
   * Image field in *Blog → Default → Primary → Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blog[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Blog → Default → Primary → Blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blog[].heading
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  heading: prismic.LinkField;

  /**
   * Description field in *Blog → Default → Primary → Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blog[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Blog → Default → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Heading field in *Blog → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Blog field in *Blog → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.default.primary.blog[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  blog: prismic.GroupField<Simplify<BlogSliceDefaultPrimaryBlogItem>>;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Item in *Contact → Default → Primary → Contact*
 */
export interface ContactSliceDefaultPrimaryContactItem {
  /**
   * Phone field in *Contact → Default → Primary → Contact*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact[].phone
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  phone: prismic.NumberField;

  /**
   * Calls field in *Contact → Default → Primary → Contact*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact[].calls
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  calls: prismic.NumberField;

  /**
   * Email field in *Contact → Default → Primary → Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → Address*
 */
export interface ContactSliceDefaultPrimaryAddressItem {
  /**
   * OfficeAddress field in *Contact → Default → Primary → Address*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.address[].officeaddress
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  officeaddress: prismic.RichTextField;

  /**
   * Pincode field in *Contact → Default → Primary → Address*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.address[].pincode
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  pincode: prismic.NumberField;

  /**
   * Timings field in *Contact → Default → Primary → Address*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.address[].timings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  timings: prismic.KeyTextField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Location field in *Contact → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;

  /**
   * Contact field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryContactItem>>;

  /**
   * Address field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.address[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  address: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryAddressItem>>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *ContentList → Default → Primary*
 */
export interface ContentListSliceDefaultPrimary {
  /**
   * Content Type field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: content_list.default.primary.content_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_type: prismic.SelectField<"Blogs" | "Our Programs">;

  /**
   * View More Text field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_list.default.primary.view_more_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  view_more_text: prismic.KeyTextField;
}

/**
 * Default variation for ContentList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentList*
 */
type ContentListSliceVariation = ContentListSliceDefault;

/**
 * ContentList Shared Slice
 *
 * - **API ID**: `content_list`
 * - **Description**: ContentList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentListSlice = prismic.SharedSlice<
  "content_list",
  ContentListSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Questions*
 */
export interface FaqSliceDefaultPrimaryQuestionsItem {
  /**
   * Description field in *Faq → Default → Primary → Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Faq → Default → Primary → Questions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Heading field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Questions field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQuestionsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *FreeTrial → Default → Primary → Title*
 */
export interface FreeTrialSliceDefaultPrimaryTitleItem {
  /**
   * Sub Heading field in *FreeTrial → Default → Primary → Title*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.title[].sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Heading field in *FreeTrial → Default → Primary → Title*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.title[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Link label field in *FreeTrial → Default → Primary → Title*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.title[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *FreeTrial → Default → Primary → Title*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.title[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *FreeTrial → Default → Primary*
 */
export interface FreeTrialSliceDefaultPrimary {
  /**
   * Title field in *FreeTrial → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.title[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  title: prismic.GroupField<Simplify<FreeTrialSliceDefaultPrimaryTitleItem>>;

  /**
   * Image field in *FreeTrial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Overtext field in *FreeTrial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_trial.default.primary.overtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  overtext: prismic.KeyTextField;
}

/**
 * Default variation for FreeTrial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FreeTrialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FreeTrialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FreeTrial*
 */
type FreeTrialSliceVariation = FreeTrialSliceDefault;

/**
 * FreeTrial Shared Slice
 *
 * - **API ID**: `free_trial`
 * - **Description**: FreeTrial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FreeTrialSlice = prismic.SharedSlice<
  "free_trial",
  FreeTrialSliceVariation
>;

/**
 * Item in *Gallery → Default → Primary → Gallery Text*
 */
export interface GallerySliceDefaultPrimaryGalleryTextItem {
  /**
   * Heading field in *Gallery → Default → Primary → Gallery Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_text[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Gallery → Default → Primary → Gallery Text*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_text[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Gallery → Default → Primary → Gallery Image*
 */
export interface GallerySliceDefaultPrimaryGalleryImageItem {
  /**
   * Image1 field in *Gallery → Default → Primary → Gallery Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_image[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image2 field in *Gallery → Default → Primary → Gallery Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_image[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *Gallery → Default → Primary → Gallery Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_image[].image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Item in *Gallery → Default → Primary → Gallery Description*
 */
export interface GallerySliceDefaultPrimaryGalleryDescriptionItem {
  /**
   * Image field in *Gallery → Default → Primary → Gallery Description*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_description[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image2 field in *Gallery → Default → Primary → Gallery Description*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_description[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image Description field in *Gallery → Default → Primary → Gallery Description*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_description[].image_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_description: prismic.RichTextField;

  /**
   * Name field in *Gallery → Default → Primary → Gallery Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_description[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Gallery → Default → Primary → Gallery Description*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_description[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Image field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Gallery Text field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_text: prismic.GroupField<
    Simplify<GallerySliceDefaultPrimaryGalleryTextItem>
  >;

  /**
   * Gallery Image field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_image: prismic.GroupField<
    Simplify<GallerySliceDefaultPrimaryGalleryImageItem>
  >;

  /**
   * Gallery Description field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_description[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_description: prismic.GroupField<
    Simplify<GallerySliceDefaultPrimaryGalleryDescriptionItem>
  >;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Item in *GalleryPage → Default → Primary → Image*
 */
export interface GalleryPageSliceDefaultPrimaryImageItem {
  /**
   * Image field in *GalleryPage → Default → Primary → Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.default.primary.image[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *GalleryPage → Default → Primary*
 */
export interface GalleryPageSliceDefaultPrimary {
  /**
   * Heading field in *GalleryPage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *GalleryPage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *GalleryPage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.default.primary.image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image: prismic.GroupField<Simplify<GalleryPageSliceDefaultPrimaryImageItem>>;
}

/**
 * Default variation for GalleryPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryPage*
 */
type GalleryPageSliceVariation = GalleryPageSliceDefault;

/**
 * GalleryPage Shared Slice
 *
 * - **API ID**: `gallery_page`
 * - **Description**: GalleryPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryPageSlice = prismic.SharedSlice<
  "gallery_page",
  GalleryPageSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Paragraph field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Link Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Players → Default → Primary → Players*
 */
export interface PlayersSliceDefaultPrimaryPlayersItem {
  /**
   * Image field in *Players → Default → Primary → Players*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: players.default.primary.players[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Players → Default → Primary → Players*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players.default.primary.players[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Player Description field in *Players → Default → Primary → Players*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players.default.primary.players[].player_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  player_description: prismic.RichTextField;
}

/**
 * Primary content in *Players → Default → Primary*
 */
export interface PlayersSliceDefaultPrimary {
  /**
   * Heading field in *Players → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Players → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: players.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Players field in *Players → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: players.default.primary.players[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  players: prismic.GroupField<Simplify<PlayersSliceDefaultPrimaryPlayersItem>>;
}

/**
 * Default variation for Players Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlayersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlayersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Players*
 */
type PlayersSliceVariation = PlayersSliceDefault;

/**
 * Players Shared Slice
 *
 * - **API ID**: `players`
 * - **Description**: Players
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlayersSlice = prismic.SharedSlice<
  "players",
  PlayersSliceVariation
>;

/**
 * Item in *Program → Default → Primary → Basketball Card*
 */
export interface ProgramSliceDefaultPrimaryBasketballCardItem {
  /**
   * Basketball Card Image field in *Program → Default → Primary → Basketball Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.basketball_card[].basketball_card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  basketball_card_image: prismic.ImageField<never>;

  /**
   * Basketball Card Heading field in *Program → Default → Primary → Basketball Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.basketball_card[].basketball_card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  basketball_card_heading: prismic.KeyTextField;

  /**
   * Basketball Card Description field in *Program → Default → Primary → Basketball Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.basketball_card[].basketball_card_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  basketball_card_description: prismic.RichTextField;
}

/**
 * Item in *Program → Default → Primary → Community Card *
 */
export interface ProgramSliceDefaultPrimaryCommunityCardItem {
  /**
   * Community Card Image field in *Program → Default → Primary → Community Card *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.community_card[].community_card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  community_card_image: prismic.ImageField<never>;

  /**
   * Community Card Heading field in *Program → Default → Primary → Community Card *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.community_card[].community_card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  community_card_heading: prismic.KeyTextField;

  /**
   * Community Card Description field in *Program → Default → Primary → Community Card *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.community_card[].community_card_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  community_card_description: prismic.RichTextField;
}

/**
 * Primary content in *Program → Default → Primary*
 */
export interface ProgramSliceDefaultPrimary {
  /**
   * Image field in *Program → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * SmallImage field in *Program → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.smallimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  smallimage: prismic.ImageField<never>;

  /**
   * Sub Heading field in *Program → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Heading field in *Program → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Program → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Basketball Card field in *Program → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.basketball_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  basketball_card: prismic.GroupField<
    Simplify<ProgramSliceDefaultPrimaryBasketballCardItem>
  >;

  /**
   * Community Card  field in *Program → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: program.default.primary.community_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  community_card: prismic.GroupField<
    Simplify<ProgramSliceDefaultPrimaryCommunityCardItem>
  >;
}

/**
 * Default variation for Program Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProgramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Program*
 */
type ProgramSliceVariation = ProgramSliceDefault;

/**
 * Program Shared Slice
 *
 * - **API ID**: `program`
 * - **Description**: Program
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramSlice = prismic.SharedSlice<
  "program",
  ProgramSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Coaches*
 */
export interface TeamSliceDefaultPrimaryCoachesItem {
  /**
   * Image field in *Team → Default → Primary → Coaches*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.coaches[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Team → Default → Primary → Coaches*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.coaches[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Designation field in *Team → Default → Primary → Coaches*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.coaches[].designation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  designation: prismic.RichTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Coaches field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.coaches[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  coaches: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryCoachesItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *Training → Default → Primary → Plans*
 */
export interface TrainingSliceDefaultPrimaryPlansItem {
  /**
   * Image field in *Training → Default → Primary → Plans*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.plans[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Training → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.plans[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Price field in *Training → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.plans[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Description field in *Training → Default → Primary → Plans*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.plans[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Training → Default → Primary*
 */
export interface TrainingSliceDefaultPrimary {
  /**
   * Heading field in *Training → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Training → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Plans field in *Training → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: training.default.primary.plans[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  plans: prismic.GroupField<Simplify<TrainingSliceDefaultPrimaryPlansItem>>;
}

/**
 * Default variation for Training Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrainingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Training*
 */
type TrainingSliceVariation = TrainingSliceDefault;

/**
 * Training Shared Slice
 *
 * - **API ID**: `training`
 * - **Description**: Training
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingSlice = prismic.SharedSlice<
  "training",
  TrainingSliceVariation
>;

/**
 * Primary content in *Welcome → Default → Primary*
 */
export interface WelcomeSliceDefaultPrimary {
  /**
   * Image field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Description field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Welcome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WelcomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Welcome*
 */
type WelcomeSliceVariation = WelcomeSliceDefault;

/**
 * Welcome Shared Slice
 *
 * - **API ID**: `welcome`
 * - **Description**: Welcome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeSlice = prismic.SharedSlice<
  "welcome",
  WelcomeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationsItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryAboutCardsItem,
      AboutSliceDefaultPrimaryTrainerItem,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimaryBlogItem,
      BlogSliceDefaultPrimary,
      BlogSliceVariation,
      BlogSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimaryContactItem,
      ContactSliceDefaultPrimaryAddressItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      ContentListSlice,
      ContentListSliceDefaultPrimary,
      ContentListSliceVariation,
      ContentListSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryQuestionsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      FreeTrialSlice,
      FreeTrialSliceDefaultPrimaryTitleItem,
      FreeTrialSliceDefaultPrimary,
      FreeTrialSliceVariation,
      FreeTrialSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimaryGalleryTextItem,
      GallerySliceDefaultPrimaryGalleryImageItem,
      GallerySliceDefaultPrimaryGalleryDescriptionItem,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      GalleryPageSlice,
      GalleryPageSliceDefaultPrimaryImageItem,
      GalleryPageSliceDefaultPrimary,
      GalleryPageSliceVariation,
      GalleryPageSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PlayersSlice,
      PlayersSliceDefaultPrimaryPlayersItem,
      PlayersSliceDefaultPrimary,
      PlayersSliceVariation,
      PlayersSliceDefault,
      ProgramSlice,
      ProgramSliceDefaultPrimaryBasketballCardItem,
      ProgramSliceDefaultPrimaryCommunityCardItem,
      ProgramSliceDefaultPrimary,
      ProgramSliceVariation,
      ProgramSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryCoachesItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TrainingSlice,
      TrainingSliceDefaultPrimaryPlansItem,
      TrainingSliceDefaultPrimary,
      TrainingSliceVariation,
      TrainingSliceDefault,
      WelcomeSlice,
      WelcomeSliceDefaultPrimary,
      WelcomeSliceVariation,
      WelcomeSliceDefault,
    };
  }
}
